Lesson8/Models/TddBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lesson8.Models
{
    //tạo ra cấu trúc bảng book
    public class TddBook
    {
        [Key]
        public int TddBookId { get; set; }
        public string TddTitle { get; set; }
        public string TddAuthor { get; set; }
        public int TddYear { get; set; }
        public string TddPublisher { get; set; }
        public string TddPicture { get; set; }
        public int TddCategoryId { get; set; }
        //thuộc tính quan hệ
        public virtual TddCategory TddCategory { get; set; }
    }
}

Lesson8/Models/TddBookStore.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Lesson8.Models
{
    public class TddBookStore:DbContext 
    {
        public TddBookStore() : base("TddBookStoreConnectionString") { }

        //tạo các bảng
        //khai báo các thuộc tính trong bảng csdl

        public DbSet<TddCategory> TddCategories { get; set; }
        public DbSet<TddBook> TddBooks { get; set; }

    }
}

Lesson8/Models/TddCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lesson8.Models
{
    public class TddCategory
    {
        /// <sumary>
        /// tạo cấu trúc bảng dữ liệu
        /// <sumary>
        [Key]
        public int TddCategoryId { get; set; }
        public int TddCategoryName { get; set; }

        //thuộc tính quan hệ
        public virtual ICollection<TddBook> TddBooks { get; set; }
    }
}

Lesson8/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson8.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lesson8/Controllers/TddBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lesson8.Models;

namespace Lesson8.Controllers
{
    public class TddBooksController : Controller
    {
        private TddBookStore db = new TddBookStore();

        // GET: TddBooks
        public ActionResult TddIndex()
        {
            var tddBooks = db.TddBooks.Include(t => t.TddCategory);
            return View(tddBooks.ToList());
        }

        // GET: TddBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TddBook tddBook = db.TddBooks.Find(id);
            if (tddBook == null)
            {
                return HttpNotFound();
            }
            return View(tddBook);
        }

        // GET: TddBooks/Create
        public ActionResult Create()
        {
            ViewBag.TddCategoryId = new SelectList(db.TddCategories, "TddCategoryId", "TddCategoryId");
            return View();
        }

        // POST: TddBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TddBookId,TddTitle,TddAuthor,TddYear,TddPublisher,TddPicture,TddCategoryId")] TddBook tddBook)
        {
            if (ModelState.IsValid)
            {
                db.TddBooks.Add(tddBook);
                db.SaveChanges();
                return RedirectToAction("TddIndex");
            }

            ViewBag.TddCategoryId = new SelectList(db.TddCategories, "TddCategoryId", "TddCategoryId", tddBook.TddCategoryId);
            return View(tddBook);
        }

        // GET: TddBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TddBook tddBook = db.TddBooks.Find(id);
            if (tddBook == null)
            {
                return HttpNotFound();
            }
            ViewBag.TddCategoryId = new SelectList(db.TddCategories, "TddCategoryId", "TddCategoryId", tddBook.TddCategoryId);
            return View(tddBook);
        }

        // POST: TddBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TddBookId,TddTitle,TddAuthor,TddYear,TddPublisher,TddPicture,TddCategoryId")] TddBook tddBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tddBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("TddIndex");
            }
            ViewBag.TddCategoryId = new SelectList(db.TddCategories, "TddCategoryId", "TddCategoryId", tddBook.TddCategoryId);
            return View(tddBook);
        }

        // GET: TddBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TddBook tddBook = db.TddBooks.Find(id);
            if (tddBook == null)
            {
                return HttpNotFound();
            }
            return View(tddBook);
        }

        // POST: TddBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TddBook tddBook = db.TddBooks.Find(id);
            db.TddBooks.Remove(tddBook);
            db.SaveChanges();
            return RedirectToAction("TddIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lesson8/Controllers/TddCategoryController.cs
using Lesson8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson8.Controllers
{
    public class TddCategoryController : Controller
    {
        private static TddBookStore _TddBookStore;
        public TddCategoryController()
        {
            _TddBookStore = new TddBookStore();
        }
        // GET: TddCategory
        public ActionResult TddIndex()
        {
            var tddCategory = _TddBookStore.TddCategories.ToList();
            return View(tddCategory);
        }
        [HttpGet]
        public ActionResult TddCreate()
        {
            var tddCategory = new TddCategory();
            return View(tddCategory);
        }
        [HttpPost]
        public ActionResult TddCreate(TddCategory tddCategory)
        {
            _TddBookStore.TddCategories.Add(tddCategory);
            _TddBookStore.SaveChanges();
            return RedirectToAction("TddIndex");
        }
    }
}

Lesson8/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
    <pre>
        Mã sinh viên:
        Họ và tên: Trần Đăng Dương    
        Ngày Sinh:
        Điện Thoại:
        Email:
    </pre>
</main>

Lesson8/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lesson8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trần Đăng Dương</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trần Đăng Dương", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("TDD: Danh sách Category", "TddIndex", "TddCategory")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Trần Đăng Dương</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>